
import { CoffeeProduct, CoffeeCategory } from './types';

export const PRODUCTS: CoffeeProduct[] = [
  {
    id: '1',
    name: 'Brazilian Santos',
    category: CoffeeCategory.ARABICA,
    origin: 'Brazil',
    price: 24.00,
    rating: 4.8,
    description: 'A smooth, mild coffee with hints of nuts and chocolate.',
    longDescription: 'Sourced from the lush rolling hills of Brazil, our Santos beans are meticulously dried in the sun to lock in a creamy body and sweet nutty profile. It is the gold standard for those who appreciate a classic cup.',
    flavorNotes: ['Nutty', 'Chocolate', 'Creamy'],
    roastLevel: 3,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['French Press', 'Drip', 'Espresso'],
    reviewsCount: 128
  },
  {
    id: '2',
    name: 'Colombian Supremo',
    category: CoffeeCategory.ARABICA,
    origin: 'Colombia',
    price: 26.50,
    rating: 4.9,
    description: 'Perfectly balanced with bright acidity and a sweet caramel finish.',
    longDescription: 'The Supremo is our highest grade of Colombian coffee. Grown at high altitudes in the Andes, these beans provide a sophisticated brightness that is perfectly countered by deep caramel undertones.',
    flavorNotes: ['Citrus', 'Caramel', 'Sweet'],
    roastLevel: 3,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['V60 Pour Over', 'Chemex', 'AeroPress'],
    reviewsCount: 245
  },
  {
    id: '3',
    name: 'Ethiopian Yirgacheffe',
    category: CoffeeCategory.ARABICA,
    origin: 'Ethiopia',
    price: 29.00,
    rating: 5.0,
    description: 'Floral, citrusy, and tea-like elegance from the birthplace of coffee.',
    longDescription: 'Widely considered some of the finest beans in the world, Yirgacheffe offers a complex bouquet of jasmine and lemon. It is light, refreshing, and deeply aromatic.',
    flavorNotes: ['Floral', 'Jasmine', 'Lemon'],
    roastLevel: 2,
    image: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['Pour Over', 'Cold Brew', 'Siphon'],
    reviewsCount: 312
  },
  {
    id: '4',
    name: 'Yemeni Mokha',
    category: CoffeeCategory.ORIGIN,
    origin: 'Yemen',
    price: 45.00,
    rating: 4.7,
    description: 'Wild, complex, and chocolatey with a history dating back centuries.',
    longDescription: 'One of the oldest known coffees in history. Grown in the rugged mountains of Yemen using ancient methods, these beans possess a unique earthy sweetness and a natural chocolate finish.',
    flavorNotes: ['Earthy', 'Dark Chocolate', 'Spice'],
    roastLevel: 4,
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['Moka Pot', 'Turkish Ibrik', 'French Press'],
    reviewsCount: 89
  },
  {
    id: '5',
    name: 'Vietnamese Robusta',
    category: CoffeeCategory.ROBUSTA,
    origin: 'Vietnam',
    price: 18.00,
    rating: 4.5,
    description: 'Bold, high caffeine, and incredibly smooth with a nutty bite.',
    longDescription: 'Our premium Robusta beans from Vietnam provide that bold energy kick without the bitterness often associated with the species. Deeply flavorful and perfect for traditional Phin coffee.',
    flavorNotes: ['Toasted Nut', 'Heavy Body', 'Cacao'],
    roastLevel: 5,
    image: 'https://images.unsplash.com/photo-1580933073521-dc49ac0d4e6a?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['Vietnamese Phin', 'Espresso', 'Iced Coffee'],
    reviewsCount: 156
  },
  {
    id: '6',
    name: 'Italian Espresso Blend',
    category: CoffeeCategory.BLEND,
    origin: 'Italy (Roasted)',
    price: 22.00,
    rating: 4.8,
    description: 'The definitive crema-rich blend for the perfect morning espresso.',
    longDescription: 'A masterfully curated blend of Arabica and a touch of premium Robusta. Roasted in the traditional Northern Italian style to ensure a thick, golden crema and a long-lasting finish.',
    flavorNotes: ['Smoky', 'Molasses', 'Thick Crema'],
    roastLevel: 5,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['Espresso Machine', 'Moka Pot'],
    reviewsCount: 420
  },
  {
    id: '7',
    name: 'Turkish Coffee Premium',
    category: CoffeeCategory.BLEND,
    origin: 'Multiple',
    price: 21.00,
    rating: 4.9,
    description: 'Extra-fine grind ready for the traditional Cezve preparation.',
    longDescription: 'A heritage blend designed specifically for Turkish coffee. It is medium roasted and stone-ground to an impalpable powder, ensuring the traditional frothy foam and rich texture.',
    flavorNotes: ['Cardamom', 'Sweet Earth', 'Balanced'],
    roastLevel: 3,
    image: 'https://images.unsplash.com/photo-1541173235-03f3481234b3?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['Cezve / Ibrik'],
    reviewsCount: 198
  },
  {
    id: '8',
    name: 'Kenyan AA',
    category: CoffeeCategory.ARABICA,
    origin: 'Kenya',
    price: 32.00,
    rating: 4.9,
    description: 'Known for its intense flavor, full body, and pleasant winey acidity.',
    longDescription: 'The AA grade denotes the largest beans from the crop. Grown in the high altitude volcanic soils of Mount Kenya, these beans offer a bold, fruit-forward experience unlike any other.',
    flavorNotes: ['Blackcurrant', 'Winey', 'Bright'],
    roastLevel: 2,
    image: 'https://images.unsplash.com/photo-1506372023823-741c83b836fe?q=80&w=800&auto=format&fit=crop',
    brewingRecs: ['V60', 'Chemex'],
    reviewsCount: 167
  }
];
